---
- name: '[dependencies] Install ohmyzsh dependencies for non-Darwin systems: zsh, git'
  ansible.builtin.package:
    name: ['zsh', 'git', 'bc']
    state: present
  become: true  # disable this for MacOS
  register: ohmyzsh_dep_result
  until: ohmyzsh_dep_result is succeeded
  when: "'Darwin' not in ansible_os_family"
  tags:
    - ohmyzsh
    - ohmyzsh_dependencies

- name: '[dependencies] Make sure locales package is installed on Debian'
  ansible.builtin.apt: name=locales state=present
  register: ohmyzsh_dep_result
  until: ohmyzsh_dep_result is succeeded
  when: "'Debian' in ansible_os_family"
  tags:
    - ohmyzsh
    - ohmyzsh_dependencies

# MacOS:
- name: '[dependencies] Install powerlevel9k dependencies: bc'
  community.general.homebrew: name=bc state=present
  become: false  # always the case with homebrew
  register: ohmyzsh_dep_result
  until: ohmyzsh_dep_result is succeeded
  when:
    - ohmyzsh_powerlevel9k
    - "'Darwin' in ansible_os_family"
  tags:
    - ohmyzsh
    - ohmyzsh_dependencies

- name: '[dependencies] Get correct brew prefix'
  ansible.builtin.command: 'brew --prefix'
  environment:
    PATH: "/opt/homebrew/bin:/usr/local/bin:{{ ansible_env.PATH }}"
  register: ohmyzsh_brew_prefix
  changed_when: false
  tags:
    - ohmyzsh
    - ohmyzsh_dependencies

- name: '[dependencies] Install fzf'
  community.general.homebrew: name=fzf state=present
  become: false  # always the case with homebrew
  register: ohmyzsh_dep_result
  until: ohmyzsh_dep_result is succeeded
  when:
    - "'Darwin' in ansible_os_family"
  tags:
    - ohmyzsh
    - ohmyzsh_dependencies

- name: '[dependencies] Install fzf useful key bindings and fuzzy completion'
  ansible.builtin.command: "{{ ohmyzsh_brew_prefix.stdout }}/opt/fzf/install --key-bindings --completion --update-rc"
  changed_when: false
  when:
    - "'Darwin' in ansible_os_family"
  tags:
    - ohmyzsh
    - ohmyzsh_dependencies

- name: '[dependencies] Install zsh on MacOS'
  community.general.homebrew: name=zsh state=present
  become: false
  register: ohmyzsh_dep_result
  until: ohmyzsh_dep_result is succeeded
  when: "'Darwin' in ansible_os_family"
  tags:
    - ohmyzsh
    - ohmyzsh_dependencies
