---
#=========================== CONFIG RELATED ============================
# music directory can also be nfs share if mpd built --with-libnfs
#   mpd_music_dir: nfs://192.168.1.1/music
mpd_music_dir: /Volumes/music                 # default: ~/music
mpd_playlist_dir: /Volumes/music/playlists    # default:  ~/.mpd/playlists

mpd_db_file: ~/.mpd/mpd.db
mpd_sticker_file: ~/.mpd/sticker.db
mpd_log_file: ~/.mpd/mpd.log
mpd_pid_file: ~/.mpd/mpd.pid
mpd_state_file: ~/.mpd/mpdstate

mpd_user: "{{ ansible_user_id }}"

mpd_outputs:
# OSX DRIVER
- name: "CoreAudio"
  type: "osx"
  mixer_type: "software"

# FIFO DRIVER (for visualizer)
- name: "FIFO"
  type: "fifo"
  path: "/tmp/mpd.fifo"
  format: "44100:16:2"

# HTTP STREAM
#- name: "http stream"
#  type: "httpd"
#  encoder: "vorbis"
#  port: "6660"
#  quality: "2"
#  format: "44100:16:2"
#=======================================================================
