---
# ============ CONFIG RELATED ==============
# music directory can also be nfs share if mpd built --with-libnfs
#   mpd_music_dir: nfs://192.168.1.1/music
mpd_music_dir: "/Users/{{ ansible_user_id }}/Music/music_lib"     # default: ~/music
mpd_playlist_dir: "/Users/{{ ansible_user_id }}/Music/playlists"  # default:  ~/.mpd/playlists
mpd_db_file: ~/.mpd/mpd.db
mpd_sticker_file: ~/.mpd/sticker.db
mpd_log_file: ~/.mpd/mpd.log
mpd_pid_file: ~/.mpd/mpd.pid
mpd_state_file: ~/.mpd/mpdstate
mpd_user: "{{ ansible_user_id }}"
mpd_outputs:
  - name: "CoreAudio"
    type: "osx"
    mixer_type: "software"
  - name: "FIFO_Visualizer"
    type: "fifo"
    path: "/tmp/mpd.fifo"
    format: "44100:16:2"
